import { useState } from 'react';
import { Link } from 'react-router-dom';
import type { Account, Initiative, Opportunity, Stakeholder } from '../types';
import { Badge } from './ui';
import { useI18n } from '../i18n';

export default function InitiativeChain({ account, initiative, opportunities, stakeholders }: { account: Account; initiative: Initiative; opportunities: Opportunity[]; stakeholders: Stakeholder[] }) {
  const { t, tv } = useI18n();
  const [showEvidence, setShowEvidence] = useState(false); const useCases = account.useCases.filter((item) => item.initiativeId === initiative.id); const targetIds = [...new Set(useCases.flatMap((item) => item.targetStakeholderIds || []))]; const targets = stakeholders.filter((item) => targetIds.includes(item.id)); const linkedOpps = opportunities.filter((item) => item.initiativeId === initiative.id);
  const fallback = (value?: string | null) => value || tv('UNKNOWN — VALIDATION REQUIRED');
  const node = (label: string, value: React.ReactNode, extra?: React.ReactNode) => <div className="chain-node"><span>{label}</span><strong>{value}</strong>{extra}</div>;
  return <article className="initiative-chain"><div className="chain-heading"><Badge tone="category-SOURCE-BASED INTERPRETATION">{tv(initiative.area)}</Badge><h3>{initiative.name}</h3></div><div className="chain-flow">
    {node(t('accounts.strategicInitiatives'), initiative.name)}<span className="chain-arrow">→</span>{node(t('chain.businessObjective'), fallback(initiative.businessObjective))}<span className="chain-arrow">→</span>{node(t('chain.currentSituation'), fallback(initiative.currentSituation))}<span className="chain-arrow">→</span><button className="chain-node chain-button" onClick={() => setShowEvidence((value) => !value)}><span>{t('chain.evidence')} ({initiative.evidence.length})</span><strong>{showEvidence ? t('chain.hideSources') : t('chain.expandSources')}</strong></button><span className="chain-arrow">→</span>{node(t('chain.potentialProblem'), <><span>{fallback(initiative.potentialProblem)}</span> <Badge tone="warning">{tv(initiative.problemCategory || 'SALES HYPOTHESIS')}</Badge></>)}<span className="chain-arrow">→</span>{node(t('chain.potentialImplication'), fallback(initiative.potentialImplication))}<span className="chain-arrow">→</span>{node(t('chain.cognitionRelevance'), fallback(initiative.cognitionRelevance))}</div>{showEvidence && <div className="chain-evidence">{initiative.evidence.map((item, index) => <div key={index}><Badge tone={`category-${item.category}`}>{tv(item.category)}</Badge><span>{item.claim}</span><small>{item.source} · {tv(item.date || 'UNKNOWN')}</small></div>)}</div>}<div className="chain-links"><div><span>{t('chain.linkedUseCases')}</span>{useCases.length ? useCases.map((item) => <Link to={`/use-cases?focus=${item.id}`} key={item.id}>{item.name}</Link>) : <small>{fallback()}</small>}</div><div><span>{t('chain.targetStakeholders')}</span>{targets.length ? targets.map((item) => <Link to={`/stakeholders/${item.id}`} key={item.id}>{item.name}</Link>) : <small>{fallback()}</small>}</div><div><span>{t('chain.opportunities')}</span>{linkedOpps.length ? linkedOpps.map((item) => <Link to={`/opportunities/${item.id}`} key={item.id}>{item.name}</Link>) : <small>{fallback()}</small>}</div></div></article>;
}
